# Single image for the whole NSW Agency service: builds the frontend, ships it
# next to the Go binary, and serves both the API and the SPA from one process.
# This is the ONLY Dockerfile — backend/ and frontend/ no longer build separately.
#
# Build context is the repo ROOT (so both backend/ and frontend/ are reachable):
#   docker build -t agency .
#
# Runtime config (/runtime-env.js, window.__APP_CONFIG__) is generated by the Go
# server per request from the environment — no entrypoint script, no file is
# written at runtime.

# BUILD_VERSION is passed by CI (git tag for releases, dev-<run>-<sha> for dev
# builds — see .github/workflows/release.yml and build-dev.yml) and baked into
# both the frontend bundle and the Go binaries below. Defaults to "dev" for
# local/unversioned builds.
ARG BUILD_VERSION=dev

# ---- Stage 1: build the frontend SPA -----------------------------------------
# Pinned to $BUILDPLATFORM: `vite build` emits only text assets, so dist/ is
# architecture-independent and one native build serves every target. This also
# keeps the arch-specific SWC/oxide/lightningcss binaries off QEMU.
FROM --platform=$BUILDPLATFORM node:22-alpine3.24 AS frontend-builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app

RUN corepack enable

COPY frontend/package.json frontend/pnpm-lock.yaml frontend/pnpm-workspace.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

COPY frontend/ .

# Vite only exposes VITE_-prefixed env vars to client code (import.meta.env),
# baking the value into the static bundle at build time. Declared here rather
# than at the top of the stage because it changes every CI run, and an ARG
# invalidates every layer beneath it — including `pnpm install` above.
ARG BUILD_VERSION
ENV VITE_APP_VERSION=$BUILD_VERSION
RUN pnpm build

# ---- Stage 2: build the Go binaries ------------------------------------------
# Patch pinned to match backend/go.mod.
# Pinned to $BUILDPLATFORM so the toolchain runs natively and cross-compiles to
# the target arch (see GOOS/GOARCH below) rather than running emulated once per
# platform. Safe because every build below sets CGO_ENABLED=0.
FROM --platform=$BUILDPLATFORM golang:1.26.4-alpine3.24 AS backend-builder

WORKDIR /app

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/ .

# -ldflags="-s -w" strips the symbol table and DWARF debug info to shrink the
# binaries. Go panic traces (function + line) and pprof still work, since they
# use the runtime pclntab rather than the symbol table. -X sets the version
# package's build-time variable, surfaced via GET /health.
# CGO_ENABLED=0: no package in the build graph needs cgo, so the binaries are
# static — which is also what makes cross-compiling to TARGETARCH viable.
# These ARGs are declared here, not at the top of the stage: an ARG invalidates
# every layer beneath it, so keeping them low leaves `go mod download` and the
# source COPY above shared by every target platform.
ARG TARGETOS
ARG TARGETARCH
ARG BUILD_VERSION
RUN LDFLAGS="-s -w -X 'github.com/OpenNSW/agency/backend/internal/version.version=${BUILD_VERSION}'" \
  && export CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
  && go build -ldflags="$LDFLAGS" -o /out/agency ./cmd/server \
  && go build -ldflags="$LDFLAGS" -o /out/migrate ./cmd/migrate \
  && go build -ldflags="$LDFLAGS" -o /out/nswac ./cmd/cli

# ---- Stage 3: runtime --------------------------------------------------------
FROM alpine:3.24

LABEL org.opencontainers.image.source="https://github.com/OpenNSW/agency"
LABEL org.opencontainers.image.description="NSW Agency service (backend API + officer portal)"

# /app is root-owned and read-only, so the process cannot replace its own binaries
# or the SPA. /data is the only writable path, group-0 owned for assigned UIDs.
RUN apk add --no-cache ca-certificates tzdata \
  && addgroup -g 1001 -S appuser \
  && adduser -u 1001 -S -D -H -h /app -s /bin/false -G appuser appuser \
  && mkdir -p /app /app/web /data \
  && chown -R 0:0 /app \
  && chown 1001:0 /data \
  && chmod g+w /data

WORKDIR /app

# Go binaries
COPY --from=backend-builder --chown=0:0 /out/agency /app/agency
COPY --from=backend-builder --chown=0:0 /out/migrate /app/migrate
COPY --from=backend-builder /out/nswac /usr/local/bin/nswac
COPY --from=backend-builder --chown=0:0 /app/migrations /app/migrations

# Task configs and forms are NOT baked into the image. They are fetched at
# runtime by the artifact loader from an external source (local mount, GitHub,
# or S3/R2), selected via ARTIFACT_LOADER_TYPE. See backend/.env.example.

# Built frontend, served (read-only) by the Go binary. The server resolves its
# asset dir as "web" relative to WORKDIR (/app), so it must land at /app/web.
# /runtime-env.js is generated dynamically from the environment, so nothing is
# written into this directory at runtime.
COPY --from=frontend-builder --chown=0:0 /app/dist /app/web

# Numeric so the kubelet can check it against runAsNonRoot.
USER 1001

# Single port serves both API and SPA (override via PORT env var)
EXPOSE 8081

# No ENTRYPOINT: the migrate Job reuses this image by overriding CMD with
# ["/app/migrate","up"]; the default runs the agency server.
CMD ["/app/agency"]
